export const STORE_FIELDS = [
  "id",
  "projeto_id",
  "slug",
  "nome",
  "titulo",
  "texto_principal",
  "sobre_nos",
  "cor_primaria",
  "logo_url",
  "tema",
  "ativo",
  "chat_widget_ativo",
  "chat_widget_id",
  "email_contato",
  "telefone_contato",
  "whatsapp_contato",
  "endereco",
  "footer_texto",
  "menu_links",
  "social_links",
  "destaques",
  "created_at",
  "updated_at",
].join(", ")
