insert into public.planos (
  id,
  nome,
  descricao,
  preco_mensal,
  limite_tokens_input_mensal,
  limite_tokens_output_mensal,
  limite_tokens_total_mensal,
  limite_custo_mensal,
  max_agentes,
  max_apis,
  max_whatsapp,
  ativo,
  permitir_excedente,
  custo_token_excedente,
  is_free,
  created_at,
  updated_at
)
values
  (
    'e1111111-1111-4111-8111-111111111111',
    'Free',
    'Ideal para testar',
    0,
    null,
    null,
    10000,
    null,
    1,
    1,
    1,
    true,
    false,
    0,
    true,
    now(),
    now()
  ),
  (
    'e2222222-2222-4222-8222-222222222222',
    'Starter',
    'Ideal para comecar',
    29.90,
    null,
    null,
    50000,
    null,
    1,
    3,
    1,
    true,
    false,
    0,
    false,
    now(),
    now()
  ),
  (
    'e3333333-3333-4333-8333-333333333333',
    'Pro',
    'Melhor custo-beneficio',
    79.90,
    null,
    null,
    200000,
    null,
    3,
    10,
    3,
    true,
    false,
    0,
    false,
    now(),
    now()
  ),
  (
    'e4444444-4444-4444-8444-444444444444',
    'Business',
    'Escalando',
    149.90,
    null,
    null,
    500000,
    null,
    10,
    30,
    10,
    true,
    false,
    0,
    false,
    now(),
    now()
  )
on conflict (id) do update
set
  nome = excluded.nome,
  descricao = excluded.descricao,
  preco_mensal = excluded.preco_mensal,
  limite_tokens_input_mensal = excluded.limite_tokens_input_mensal,
  limite_tokens_output_mensal = excluded.limite_tokens_output_mensal,
  limite_tokens_total_mensal = excluded.limite_tokens_total_mensal,
  limite_custo_mensal = excluded.limite_custo_mensal,
  max_agentes = excluded.max_agentes,
  max_apis = excluded.max_apis,
  max_whatsapp = excluded.max_whatsapp,
  ativo = excluded.ativo,
  permitir_excedente = excluded.permitir_excedente,
  custo_token_excedente = excluded.custo_token_excedente,
  is_free = excluded.is_free,
  updated_at = now();
